### PR TITLE
Deprecate elasticsearch type, and split it into elastica and elastic_search types

### LINKED ISSUE #424: Collision between ElasticSearchHandler and ElasticaHandler
Hi,

I'm trying to set up monolog-bundle with native Elasticsearch cliente (introduced in monolog 2.0).
But it seems that I'm doing something wrong and I can't make it work.

Reviewing the code itself I've seen the following lines in MonologExtension:

https://github.com/symfony/monolog-bundle/blob/fde12fc628162787a4e53877abadc30047fd868b/DependencyInjection/MonologExtension.php#L983-L1011

There you can see that "elasticsearch" is always replaced with the ElasticaHandler in the array merge on line 1006.
Apart from that, I think the elastic handler should be ElasticsearchHandler, not ElasticSearchHandler (note te captial "S").

I locally did those changes but couldn't make it work and I'm lost.
Does symfony/monolog-bundle support the native Elasticsearch client? Or am I doing something wrong?

Many many thanks for your help

### PR DESCRIPTION
**Pull request by Seldaek**
Fixes #424

### CODE REVIEW

File: DependencyInjection/MonologExtension.php [hunk 1]
```diff
@@ -305,38 +305,51 @@ private function buildHandler(ContainerBuilder $container, $name, array $handler
             break;
 
         case 'elasticsearch':
+        case 'elastica':
+        case 'elastic_search':
+            if ($handler['type'] === 'elasticsearch') {
+                @trigger_error('The "elasticsearch" handler type is deprecated in MonologBundle since version 3.8.0, use the "elastica" type instead, or switch to the official Elastic client using the "elastic_search" type.', E_USER_DEPRECATED);
+            }
+
```
Comment (derrabus) [inline DependencyInjection/MonologExtension.php:313]:
```suggestion
            @trigger_error('The "elasticsearch" handler type is deprecated in MonologBundle since version 3.8.0, use the "elastica" type instead, or switch to the official Elastic client using the "elastic_search" type.', E_USER_DEPRECATED);
            // no break

        case 'elastica':
        case 'elastic_search':
```

**Review by derrabus — COMMENTED** [review]
Should we add tests for this change?

**Review by stof — APPROVED** [review]

**Comment by Seldaek** [comment]
See https://github.com/symfony/monolog-bundle/commit/769b7daa4f7a350d665c9334a2c0c71a683ea7c6 for a last fix here, forgot to add the factory

**Comment by Chameleon-m** [comment]
elastic_search.host does not work, must be array
https://github.com/symfony/monolog-bundle/blob/master/DependencyInjection/MonologExtension.php#L292
need array for elastic_search, and key "hosts", example:
`
$clientArguments = [
    'hosts' => $handler['elasticsearch']['host'],
];
`
OR
`
$clientArguments = [
    'hosts' => $handler['elasticsearch']['hosts'],
];
`
And fix Configuration, host must be array|string:
https://github.com/symfony/monolog-bundle/blob/master/DependencyInjection/Configuration.php#L98
https://github.com/symfony/monolog-bundle/blob/master/DependencyInjection/Configuration.php#L879

**Comment by JulienMarliac** [comment]
Hey

I can confirm that elastic_search does not work (see @Chameleon-m message) , any plans on the fix ? Or should I open a new issue ?

**Comment by Kenneth-Sills** [comment]
[Ticket created.](https://github.com/symfony/monolog-bundle/issues/500)
