### PR TITLE
Resolve "level" env var at runtime

### LINKED ISSUE #413: Setting log_level via environment variable requires cache clear
Hi, I'm trying to use the log_level from env vars implemented in #357 but I can't seem to get it to work without clearing the cache between command executions.

I'm using v3.7 of this bundle:

```
root@9e633aa0c868:/app# composer show symfony/monolog-bundle
name     : symfony/monolog-bundle
descrip. : Symfony MonologBundle
keywords : log, logging
versions : * v3.7.0
```

I have this configuration:

```yaml
# config/packages/probe/monolog.yaml
parameters:
    log_level: "%env(APP_LOG_LEVEL)%"

monolog:
    handlers:
        main:
            type: stream
            path: php://stderr
            level: '%log_level%'
```

And I'm testing with this command:

```php
<?php
declare(strict_types=1);

namespace App\Command;

use Psr\Log\LoggerInterface;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

class TestCommand extends Command
{
    protected static $defaultName = 'app:test';
    private ContainerInterface $container;
    private LoggerInterface $logger;

    public function __construct(ContainerInterface $container, LoggerInterface $logger, string $name = null)
    {
        parent::__construct($name);
        $this->container = $container;
        $this->logger = $logger;
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $output->writeln('log_level: ' . $this->container->getParameter('log_level'));

        $this->logger->debug('debug');
        $this->logger->info('info');
        $this->logger->notice('notice');
        $this->logger->warning('warning');
        $this->logger->error('error');
        $this->logger->critical('critical');
        $this->logger->alert('alert');
        $this->logger->emergency('emergency');

        return Command::SUCCESS;
    }
}
```

I expected the APP_LOG_LEVEL to be able to change between subsequent runs of the command w/o clearing the cache, but that doesn't seem to work. As soon as I start the command with a valid value for log_level, I can never change it until I clear the cache.

This is also annoying when I already have a .env/.env.local file since it always seems to take that value.

In this example, I have APP_LOG_LEVEL=warning in the .env file.

```shell
root@9e633aa0c868:/app# APP_ENV=probe php bin/console app:test                  
log_level: warning
[2021-07-05T16:27:13.541340+00:00] app.WARNING: warning [] []
[2021-07-05T16:27:13.545269+00:00] app.ERROR: error [] []
[2021-07-05T16:27:13.547210+00:00] app.CRITICAL: critical [] []
[2021-07-05T16:27:13.548159+00:00] app.ALERT: alert [] []
[2021-07-05T16:27:13.549459+00:00] app.EMERGENCY: emergency [] []
root@9e633aa0c868:/app# APP_LOG_LEVEL=debug APP_ENV=probe php bin/console app:test
log_level: debug
[2021-07-05T16:27:17.861489+00:00] app.WARNING: warning [] []
[2021-07-05T16:27:17.864648+00:00] app.ERROR: error [] []
[2021-07-05T16:27:17.866875+00:00] app.CRITICAL: critical [] []
[2021-07-05T16:27:17.868456+00:00] app.ALERT: alert [] []
[2021-07-05T16:27:17.869008+00:00] app.EMERGENCY: emergency [] []
```

If I remove APP_LOG_LEVEL from .env *or* remove the cache and then restart my command passing APP_LOG_LEVEL=debug it'll use that value for all subsequent runs. It won't change until I clear:cache or remove the cache.

```shell
root@9e633aa0c868:/app# rm -rf var/cache/probe/*
root@9e633aa0c868:/app# APP_LOG_LEVEL=debug APP_ENV=probe php bin/console app:test                    
log_level: debug
[2021-07-05T16:28:58.107361+00:00] app.DEBUG: debug [] []
[2021-07-05T16:28:58.107665+00:00] app.INFO: info [] []
[2021-07-05T16:28:58.107821+00:00] app.NOTICE: notice [] []
[2021-07-05T16:28:58.107951+00:00] app.WARNING: warning [] []
[2021-07-05T16:28:58.108081+00:00] app.ERROR: error [] []
[2021-07-05T16:28:58.108239+00:00] app.CRITICAL: critical [] []
[2021-07-05T16:28:58.109731+00:00] app.ALERT: alert [] []
[2021-07-05T16:28:58.110578+00:00] app.EMERGENCY: emergency [] []
```

Am I doing something wrong or is this intended behavior?

### PR DESCRIPTION
**Pull request by GromNaN**
Resolves #413, #444

Currently, the log level is read when the container built. This means we cannot change a log level at runtime using env vars.

With this change, log level can be modified for a specific command run: `LOG_LEVEL=debug bin/console ...`

~I would like to get some feedbacks before updating tests. I don't know yet what is the best strategy to check the resolution of the values.~

### CODE REVIEW

File: DependencyInjection/MonologExtension.php [hunk 1]
```diff
@@ -14,6 +14,7 @@
 use Monolog\Attribute\AsMonologProcessor;
 use Monolog\Handler\FingersCrossed\ErrorLevelActivationStrategy;
 use Monolog\Handler\HandlerInterface;
+use Monolog\Level;
```
Comment (GromNaN) [inline DependencyInjection/MonologExtension.php:17]: I tried an other implementation with the enum `Monolog\Level::fromName`, but that does not work if the env var or parameter contains a number.

https://github.com/symfony/monolog-bundle/pull/446/commits/2f92e7400910a4344044d7baf98dbb952d98eb17

File: DependencyInjection/MonologExtension.php [hunk 2]
```diff
@@ -49,29 +51,19 @@ class MonologExtension extends Extension
...
-        if ($container->hasParameter($level)) {
-            return $this->levelToMonologConst($container->getParameter($level), $container);
-        }
-
-        try {
-            $logLevel = $container->resolveEnvPlaceholders($level, true);
-        } catch (ParameterNotFoundException $notFoundException) {
-            throw new \InvalidArgumentException(sprintf('Could not match "%s" to a log level.', $level));
-        }
+        if (is_string($level) && str_contains($level, '%')) {
```
Comment (GromNaN) [inline DependencyInjection/MonologExtension.php:54]: Resolution can be done at build time if it does not contains a parameter or env var.

File: MonologBundle.php [hunk 3]
```diff
@@ -50,4 +51,20 @@ public static function includeStacktraces(HandlerInterface $handler)
...
+    {
+        if (null === $level || is_numeric($level)) {
+            return $level;
+        }
+
+        if (defined('Monolog\Logger::'.strtoupper($level))) {
+            return constant('Monolog\Logger::' . strtoupper($level));
+        }
+
+        throw new \InvalidArgumentException(sprintf('Could not match "%s" to a log level.', $level));
```
Comment (GromNaN) [inline MonologBundle.php:68]: Thinking about it, the exception message could be a little more helpful if the raw string was injected (i.e. `%env(LOG_LEVEL)%`).

**Comment by uncaught** [comment]
Did you check if this is even needed?

Last time I checked, every handler already casts the log level.

I see no reason for this bundle to cast the level at all.

**Comment by GromNaN** [comment]
Why didn't I think of that! You are absolutely right.

By default the [`AbstractHandler`](https://github.com/Seldaek/monolog/blob/main/src/Monolog/Handler/AbstractHandler.php#L38) constructor calls `setLevel`, which calls `Logger::toMonologLevel($level)`.

I'll check for older versions and update the PR.

**Comment by GromNaN** [comment]
`Logger::toMonologLevel` is called [since monolog 1.11](https://github.com/Seldaek/monolog/commit/feb19af2d42ab598e3e5e77e8f4bd51b82538acb). This is safe to remove the call in the DI extension.

**Review by lyrixx — COMMENTED** [review]
I did not test the code locally, but this seems super cool 👍🏼 
Less code => more feature 🎖️

**Comment by lcobucci** [comment]
@GromNaN do you have an idea on when this will be released?
